import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class TechnologyIconService {
  private icons: Record<string, string> = {
    'HTML': '../../assets/icons/html.png',
      'CSS': '../../assets/icons/css.png',
      'JavaScript': '../../assets/icons/js.png',
      'TypeScript': '../../assets/icons/typescript.png',
      'Angular': '../../assets/icons/angular.png',
      'React': '../../assets/icons/react.png',
      'Vue.js': '../../assets/icons/react.png',
      'Svelte': '../../assets/icons/react.png',
      'Tailwind CSS': '../../assets/icons/react.png',
      'Bootstrap': '../../assets/icons/react.png',
      'Material UI': '../../assets/icons/react.png',
      'Next.js': '../../assets/icons/react.png',
      'Nuxt.js': '../../assets/icons/react.png',
      'Node.js': '../../assets/icons/react.png',
      'Express.js': '../../assets/icons/react.png',
      'Spring Boot': '../../assets/icons/react.png',
      'Java': '../../assets/icons/react.png',
      'Python': '../../assets/icons/react.png',
      'Django': '../../assets/icons/react.png',
      'Flask': '../../assets/icons/react.png',
      'Ruby on Rails': '../../assets/icons/react.png',
      '.NET': '../../assets/icons/react.png',
      'PHP': '../../assets/icons/react.png',
      'Laravel': '../../assets/icons/react.png',
      'Go': '../../assets/icons/react.png',
      'NestJS': '../../assets/icons/react.png',
      'Kotlin': '../../assets/icons/react.png',
      'PostgreSQL': '../../assets/icons/react.png',
      'MySQL': '../../assets/icons/react.png',
      'MongoDB': '../../assets/icons/react.png', 
      'SQLite': '../../assets/icons/react.png',
      'Firebase': '../../assets/icons/react.png',
      'Redis': '../../assets/icons/react.png',
      'Cassandra': '../../assets/icons/react.png',
      'MariaDB': '../../assets/icons/react.png',
      'Elasticsearch': '../../assets/icons/react.png',
      'Flutter': '../../assets/icons/react.png',
      'React Native': '../../assets/icons/react.png', 
      'Swift': '../../assets/icons/react.png', 
      'Kotlin (Android)': '../../assets/icons/react.png', 
      'Ionic': '../../assets/icons/react.png', 
      'Xamarin': '../../assets/icons/react.png',
      'Docker': '../../assets/icons/react.png',
      'Kubernetes': '../../assets/icons/react.png',
      'Git': '../../assets/icons/react.png',
      'GitLab CI/CD': '../../assets/icons/react.png',
      'GitHub Actions': '../../assets/icons/react.png',
      'Jenkins': '../../assets/icons/react.png',
      'AWS': '../../assets/icons/react.png',
      'Azure': '../../assets/icons/react.png',
      'GCP': '../../assets/icons/react.png',
      'Terraform': '../../assets/icons/react.png',
      'Ansible': '../../assets/icons/react.png',
      'Nginx': '../../assets/icons/react.png',
      'Jest': '../../assets/icons/react.png',
      'Mocha': '../../assets/icons/react.png',
      'Chai': '../../assets/icons/react.png',
      'JUnit': '../../assets/icons/react.png',
      'Cypress': '../../assets/icons/react.png',
      'Selenium': '../../assets/icons/react.png',
      'Playwright': '../../assets/icons/react.png', 
      'Postman': '../../assets/icons/react.png',
      'Figma': '../../assets/icons/react.png', 
      'Adobe XD':'../../assets/icons/xd.png',
      'Sketch': '../../assets/icons/react.png',
      'Canva': '../../assets/icons/react.png',
      'TensorFlow': '../../assets/icons/react.png', 
      'PyTorch': '../../assets/icons/react.png', 
      'Scikit-learn': '../../assets/icons/react.png',
      'Pandas': '../../assets/icons/react.png',
      'NumPy': '../../assets/icons/react.png',
      'Matplotlib': '../../assets/icons/react.png',
      'OpenCV': '../../assets/icons/react.png',
      'GraphQL': '../../assets/icons/react.png',
      'REST API': '../../assets/icons/react.png',
      'WebSockets': '../../assets/icons/react.png',
      'JSON': '../../assets/icons/react.png',
      'YAML': '../../assets/icons/react.png',
      'Markdown': '../../assets/icons/react.png', 
      'Webpack': '../../assets/icons/react.png',
      'Vite': '../../assets/icons/react.png',
      'Babel': '../../assets/icons/react.png',
      'ESLint': '../assets/icons/react.png',
      'Prettier': '../assets/icons/react.png',
  };

  getTechIcon(tech: string): string {
    return this.icons[tech] || 'assets/icons/default.png';
  }

  
}

